# Generated by Django 3.2.5 on 2021-07-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yrs_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.club')),
                ('primary_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateTimeField(verbose_name='birth date')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.group')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.member')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='tournament date')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club_manager.location')),
                ('players_list', models.ManyToManyField(to='club_manager.Player')),
                ('primary_t_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.member')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('date_elected', models.DateTimeField(verbose_name='date elected')),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club_manager.member')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.member'),
        ),
        migrations.AddField(
            model_name='club',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.location'),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.officer'),
        ),
    ]
