# Generated by Django 3.2.5 on 2021-07-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0002_alter_player_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='date',
            new_name='t_date',
        ),
        migrations.AddField(
            model_name='player',
            name='ability_level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tourn_name',
            field=models.CharField(default='Tournament', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='date_elected',
            field=models.DateField(verbose_name='date elected'),
        ),
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='club_manager.group'),
        ),
    ]
