# Generated by Django 3.2.5 on 2021-07-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0002_alter_coach_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='coach',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='officer',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='member',
        ),
    ]
