# Generated by Django 3.2.5 on 2021-07-05 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0003_auto_20210705_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='primary_coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_manager.coach'),
        ),
    ]
