# Generated by Django 3.2.5 on 2021-07-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0004_alter_group_primary_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='location',
        ),
        migrations.RemoveField(
            model_name='club',
            name='president',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='yrs_experience',
        ),
        migrations.RemoveField(
            model_name='group',
            name='primary_coach',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='date_elected',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='primary_t_director',
        ),
        migrations.AddField(
            model_name='club',
            name='club_type',
            field=models.CharField(default='Chess', max_length=50),
        ),
        migrations.AddField(
            model_name='coach',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_manager.group'),
        ),
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_manager.club'),
        ),
        migrations.AddField(
            model_name='officer',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_manager.club'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club_manager.club'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club_manager.member'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.group'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
